### PR TITLE
Added 4 pages

### PR DESCRIPTION
**Pull request by theJayBecker**
Added

- guest welcome page
- guest social media
- sign in
- sign up

### CODE REVIEW

**Comment by rorepopo** [comment]
@theJayBecker per Michael - please re-sync with Main. Once done let me know and I'll approve the PR.

**Comment by theJayBecker** [comment]
okay?

guess I'll just merge from main into my branch and then it should be synced

**Comment by rorepopo** [comment]
> okay? guess I'll just merge from main into my branch and then it should be synced
> […](#)

@theJayBecker I believe so! Let me know when it's done. :)

**Comment by theJayBecker** [comment]
@rorepopo 

done

**Comment by rorepopo** [comment]
conflicts resolved, pull request approved.

**Pull request merged**
