### PR TITLE
Added welcome, password update, manage account, and guest landing pages

### PR DESCRIPTION
**Pull request by theJayBecker**
Added welcome, password update, manage account, and guest landing pages

### CODE REVIEW

**Comment by theJayBecker** [comment]
@michael-gokey-architect 
Tried merging them, but before I did, when I rain the server on main, I got all these errors. I verified I got the right installation (angular 16) and all the right packages. Let me know how you would like me to proceed? I can fix the issues with main and then merge them with my branch or if you'd like to resolve the errors and then I merge. I am up for whatever works best for you.

Until then I'll just keep cranking out pages.

Screenshot from 2024-05-21 19-36-13

**Comment by michael-gokey-architect** [comment]
Lets close this PR.
grab the code, save them as text files over to the side.
delete your old branch. create a new one off of origns/main. pull.
Then edit your pages, and commits. and then at the end of your day, do a Pull Request, so at 6:30a, when I come on, I can approve your branch into main, and everyone is happy.
No editing Main directly

**Comment by theJayBecker** [comment]
right, okay, I'll fix whatever is wrong with main on a side branch and add in the changes.

Talk to you in the am!

**Comment by theJayBecker** [comment]
Goood morning!

Here is what happened last night.
Just to be on the safe side, I created a new branch form main fixed the issues with main merged that into s6 then merged completed the merge from s6 into main. Aaaand I also wrapped in the additional pages I made into the merge as well

Sorry about completing the merge instead of waiting for you to approve it. Instinct kicked in and realized you wanted approve it when it was too late 😅.

~Jay

**Pull request merged**
